name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # 每天 UTC 0 点运行
  workflow_dispatch:     # 允许手动触发

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 写入仓库内容的权限
    steps:
      - name: Checkout output branch
        uses: actions/checkout@v4
        with:
          ref: output
          path: output-repo

      - name: Generate snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: tangsangsimida
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Copy SVG to output branch
        run: |
          cp dist/github-contribution-grid-snake.svg output-repo/

      - name: Push to output branch
        working-directory: output-repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add github-contribution-grid-snake.svg
          git commit -m "Update snake animation [skip ci]" || echo "No changes to commit"
          git push
